language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: vfI3Og0d/FVTXsSacRhMDkGruFoVn6h5LbWRR+508RHVABfsRHxXR5S8PxZYv2xED5UjwMCQ7FNoJUd5n71mDHZYtFe3Lcdfru6P6FjQwyD8K1tCaVn0QkEFbJvjzkUPbmPtf+d4Ma4udHghD37wgiFfVLKIgMfY+KqXgEDMzAnvtczPkTVxUaXAjCUy8A5lxxF24H6Qyyn67Mc6tirnooljoEj06GdEqkzYCXqOHtxZOfB1WWzcrbBNJNlsih+93dMYcD0S0Q8+DOZZwiACsmeIqhJeX38Ct62Vw77dwllRMiXdK4JoZFdQZxgDvjEP1XF5mn2tg8ahIgB5FCq2aOp43n5QvZKiPzvJLu7WIxcKFG4sheOiJ2nCgirzNKl046aHM/3ZZfyIy5qnqAxdZAnQGlNePMExPls1mIEyCbDUYBQOuK3fkowRGS7Wbv/kLggC7jQxksRIUzZgbimdM5O5cZg/QsWXgSKI38oQO+Q8QQrrEZ29LxhjI1ZHr6WPTTh/JQhXQ7299zujY37IDCSJTvzqiXrfQnAsI10AX8mfWhYTpXrM+u6KXgkFWGB3n+yScEMX5YP1r1ogNEdIHDtADEhvXOEkMoSz+KhsnQlQhaPc7xs0gJL1uPmclSIeC32sh7eU3hkNN7KHIg95H8aFMOF6XyYP5MxEbPC+oxM=
