language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: RtdQCDobsdVxUSm5x4iNBn7OFSHvMPNYmaVjAXPIuE+HRmVGpZIjyVxjvVz5j+qv6hkoWXvyADNmIzZyzeBCMk5ebhKBjuEsvhgZpj5R1ORO7oSSvwshODwW/U5+CkrBHfVL5fwQYVOWzYLvQA4ajWf7RnGyZSsA7XXlL62vd7VzMJUXJijHqxwx98fJECv5am4aZQxiZ3RfBRR1DXOvHDHqzPuvUklTc+VJWLj1M596RspKwpjt5iJFm/k4TIdL/NZgAVbRa8vCa+Z+xCF80eQ4U1tyOREiIGSiBSHg5EXuIsUutycztosw2oZcyyyyJbamiHDv7CWl79gvLKlPLIJevUJ5LfizDL6LcrSvRDrDm86ycwy8URkZnGuGu/b9slSqVMKvven5BwDW/1cIS634FGift2PR3mls69eTgBX4BThY2/b8FRE/TMnN2o+dUhw5ar9lk4WXTNI6PVu0OdL284v/wULxfPownZLFQZkI5maYqXnRhzWiwgZzF4N9XmzyqLbhKT+DD0wqwp/vwvfGjOgFk7EszatlrORUEYb5kJF6/9Lyuw8Ol5higXVe8mcRUiweXE6DZg6yzNy8ULr3VQ2IQc6zvQRlHv3AxxXo71OQql9OKLCHD7qOpd0E8/YM3v2mD/lHpgY97mo3voobcDr6x7R4fjHQiPPmaaE=
