language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: EPONXs0UT54zNLnB+ikjhB3gYEyRuCSOLTtDk4g2VVQKMZ/arlasfwbnfH4xHd4WXy7yISn2DqQWAsK5qqga7zHkyq4cxWCXgvfkigV2Jvo35EFNGC5Vd3t7TRD0TRs+af2Ta7UXFkCXaNXLEHCHqMoY87gRvSadYuK3PCrUXNdtJzf0h8e4X4Y4YS3IFv1B6ZXx2lEeMt+SgMQe5ZhTBxbxDbLB3dfRfpn46hxZOpx3OaOF7aHHDI4B+VbFWL9kHcDW+Y0ar1PT5qDyKJX6tEKHhrZDYwHMKSA4YAIW9tJE5JZDIHOH9shPV0PxBx4/EOUA+jWsaHIio5Uhsm70wLswLKcGdJ5kxg/s3A+M2fJCCVoyqaxtwJ4N+T/stoxOtSLLPw/+UWROzctdX4jyAmMPDGTEEDveDIQxbmY6h24iS1vUShqFfC1BWw7qRxi7m6o+CmEuuNFUFMoZKyBiCb4NtVwAssvD6QqQolusp/3llrSdWKiMuyiBjyaksvlko2jzfFNsfLniNBqJLWdrggRczUZ+/61iZVLiSd13nsU0J1yH9avLsGmzUCTTi9mxF1BiZLWzaG54SwhloGUon8FvXjwF4EoTCdZKdz13I626g/uIOzIyeO+c4PB5p1BuAQXMUOi75862cWwaT+mxPAXmWbbpvSus7vOaF6eMsBc=
