language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: lFWKO64pXDizVSt/0dwEvyuR8Z/FmKPtWUtLvpjqlZ7hD1k3ACE6nCm7+vUxq+hAa4VQI/EStEsfQGTPN8N0obL1i80ZBCXvzwHffqCATylFT7aYF7fExcw8qKjOoE/+6d4YYPyPykCfW3MIszQNbHEIogyA6UfPcgaG9LDgHvQ4h/U9cXmR9s+8djMF7qNSXy+G6l7agN3iAPLNR45YYlonbzeBQy02A2Mwon3s7jyU5HzlLuoU+EoANWTx+yVm14jYdrkcY2mWDUUV3TMk6yGpTyZji+p/8dJmAOIhmraVrwetSeI0hwuN+ndGq4sJxzRUWDUNP8IrLhhOiSROdLkM0f2TfSIi4vu85tzrFM1c92yIBRtkimXQ8QCVgqlIEmvAyMdA12TKMLJtzPQIgCWR1FMsKhhQgt4yW0ty2u6yX+qZEOq01nfqa7hL1Gg56cRPY0MC1l7zJzAfFzPry8cnIJRg165ga/9bvUxEev10vfXSGR1THGZVwrKkKCm/BkHpG5S1SH5hh3ODis+Q80k6T7Q7OtAh4seSLrFtvSWG7Pdz8ZW32yEylA0b1FJ23DVv3nk4mf3/e9v3G/VXxJ5wu0lZqkdeWur+cw5swAw4BIwTqAqkf8MdXh7YpfQzrz1vrZt2jcMl4VOhvtvLw/WDlGSTT8I1ORWQb91dAJI=
